---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: docker-dry-run
    image: plugins/docker
    settings:
      repo: techknowlogick/caddy-s3browser
      dry_run: true
    when:
      event:
      - pull_request

  - name: create-test-bucket
    image: minio/mc
    commands:
    - sleep 1 # hope that minio has started by this point
    - mc config host add test http://objectstorage:9000 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
    - mc ls test
    - mc mb test/s3browser-test
    - echo "test file 1" > main.txt
    - echo "test file 12" > one.txt
    - echo "test file 123" > second.txt
    - echo "test file 1234" > another.txt
    - echo "test file 12345" > last.txt
    - mc policy download test/s3browser-test
    - mc cp main.txt test/s3browser-test
    - mc cp second.txt test/s3browser-test
    - mc cp one.txt test/s3browser-test/one/
    - mc cp another.txt test/s3browser-test/one/
    #- mc mb test/s3browser-test/one/two/
    #- mc mb test/s3browser-test/one/two/three/
    #- mc mb test/s3browser-test/one/two/three/four/
    #- mc cp another.txt test/s3browser-test/one/two
    #- mc cp another.txt test/s3browser-test/one/two/three
    - mc cp last.txt test/s3browser-test/one/two/three/four/
    #- mc rm test/s3browser-test/one/two/another.txt
    #- mc rm test/s3browser-test/one/two/three/another.txt

  - name: compile-and-run
    image: golang:1.12-alpine
    environment:
      S3_DEBUG: true
      S3_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
      S3_SECRET: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
      S3_ENDPOINT: objectstorage:9000
      S3_HOST: objectstorage
      S3_EXTRA: ":9000"
      S3_BUCKET: s3browser-test
      S3_SECURE: false
      S3_PROTO: http
      S3_REFRESH: 25s
    commands:
    - apk add wget mailcap ca-certificates gettext libintl curl git 
    - mkdir -p /go/src/src.techknowlogick.com/
    - cp -r $CI_WORKSPACE /go/src/src.techknowlogick.com/caddy-s3browser
    - cd /go/src/src.techknowlogick.com/caddy-s3browser
    - go get ./...
    - go get -d -v github.com/mholt/caddy/caddy
    - cd /go/src/github.com/mholt/caddy/caddy
    - sed -i '/This is where other plugins get plugged in (imported)/a _ "src.techknowlogick.com/caddy-s3browser"' caddymain/run.go
    - go install -v .
    - /go/bin/caddy -version
    - "envsubst < /drone/src/Caddyfile.tmpl > /drone/src/Caddyfile"
    - cat /drone/src/Caddyfile
    - /go/bin/caddy -conf /drone/src/Caddyfile &
    - sleep 3
    - "curl -v -H \"Accept: application/json\" localhost"

services:
- name: objectstorage
  image: minio/minio:RELEASE.2019-02-20T22-44-29Z
  command:
  - server
  - /data
  environment:
    MINIO_ACCESS_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
    MINIO_BROWSER: off
    MINIO_SECRET_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
