---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/src.techknowlogick.com/caddy-s3browser

steps:
  - name: docker-dry-run
    image: plugins/docker
    settings:
      repo: techknowlogick/caddy-s3browser
      dry_run: true
    when:
      event:
      - pull_request

  - name: create-test-bucket
    image: minio/mc
    commands:
    - sleep 3 # hope that minio has started by this point
    - mc config host add test http://objectstorage:9000 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
    - mc ls test
    - mc mb test/s3browser-test
    - echo "test file 1" > main.txt
    - echo "test file 12" > one.txt
    - echo "test file 123" > second.txt
    - echo "test file 1234" > another.txt
    - echo "test file 12345" > last.txt
    - mc cp main.txt test/s3browser-test
    - mc cp second.txt test/s3browser-test
    - mc cp one.txt test/s3browser-test/one
    - mc cp another.txt test/s3browser-test/one
    - mc mb test/s3browser-test/one/two/
    - mc mb test/s3browser-test/one/two/three/
    - mc mb test/s3browser-test/one/two/three/four/
    - mc cp another.txt test/s3browser-test/one/two
    - mc cp another.txt test/s3browser-test/one/two/three
    - mc cp last.txt test/s3browser-test/one/two/three/four
    - mc rm test/s3browser-test/one/two/another.txt
    - mc rm test/s3browser-test/one/two/three/another.txt

  - name: compile-and-run
    image: golang:1.12
    environment:
      S3_DEBUG: true
      S3_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
      S3_SECRET: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
      S3_ENDPOINT: objectstorage:9000
      S3_HOST: objectstorage
      S3_EXTRA: ":9000"
      S3_BUCKET: s3browser-test
      S3_SECURE: false
      S3_PROTO: http
      S3_REFRESH: 25s
    commands:
    - go get -d -v github.com/mholt/caddy/caddy
    - cd /go/src/github.com/mholt/caddy/caddy
    - sed -i '/This is where other plugins get plugged in (imported)/a _ "src.techknowlogick.com/caddy-s3browser"' caddymain/run.go
    - go install -v .
    - /go/bin/caddy -version
    - apk add curl
    - curl -v localhost

services:
- name: objectstorage
  image: minio/minio:RELEASE.2018-12-27T18-33-08Z
  command:
  - server
  - /tmp
  environment:
    MINIO_ACCESS_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
    MINIO_BROWSER: off
    MINIO_SECRET_KEY: 51bcaa680ac2fa4bb9f38bde4bf6f5620c542222393f95e2e6f6d38f838e3c17
